blog/urls.py
from django.contrib import admin
from django.urls import path
from .views import *

app_name = 'blog'

urlpatterns = [
    path('create/', index, name='index'),
    path("", articles, name='articles'),
    path("dashboard/", dashboard, name='dashboard'),
    path("addArticle/", addArticle, name='addArticle'),
    path("blog/<int:id>", detail, name='detail'),
    path('update/<int:id>', updateArticle, name='update'),
    path('delete/<int:id>', deleteArticle, name='delete'),
    path('comment/<int:id>', addComment, name='comment'),

]

kassa/urls.py
from django.urls import path
from .views import *

app_name = 'kassa'

urlpatterns = [
    path('privacy/', privacy, name='privacy'),
    path('refund/', refund, name='refund'),

]

tezbilet/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from blog.views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", index, name='index'),
    path("about/", about, name='about'),
    path("detail/<int:id>", detail, name='detail'),
    path("blog/", include("blog.urls")),
    path('user/', include('user.urls')),
    path('kassa/', include('kassa.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

user/urls.py
from django.contrib import admin
from django.urls import path
from .views import *

app_name = 'user'

urlpatterns = [
    path('register/', register, name='register'),
    path('login/', loginUser, name='login'),
    path('logout/', logoutUser, name='logout'),
]

blog/models.py
from django.db import models
from ckeditor.fields import RichTextField
from imagekit.models import ImageSpecField, ProcessedImageField
from imagekit.processors import ResizeToFill


class Blog(models.Model):
    objects = None
    author = models.ForeignKey('auth.User', on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    content = RichTextField()
    created_date = models.DateField(auto_now_add=True)
    article_image = ProcessedImageField(upload_to='blog_photos',
                                             processors=[ResizeToFill(360,300)],
                                             format='JPEG',
                                             options={'quality':60})
    article_image_thumbnail = ImageSpecField(source = 'article_image',
                                        processors=[ResizeToFill(360, 300)],
                                        format='JPEG',
                                        options={'quality': 60})

    category = models.CharField(max_length=50, null=True, blank=True)
    main_article = models.BooleanField(default=False)

    def __str__(self):
        return self.title
    class Meta:
        ordering = ['-created_date']


class Comment(models.Model):
    article = models.ForeignKey(Blog, on_delete=models.CASCADE, related_name='comments')
    comment_author = models.CharField(max_length=50)
    comment_content = models.CharField(max_length=100)
    comment_date = models.DateField(auto_now_add=True)


    def __str__(self):
        return self.comment_content

    class Meta:
        ordering = ['-comment_date']

blog/forms.py
from django import forms
from .models import Blog
class ArticleForm(forms.ModelForm):
    class Meta:
        model = Blog
        fields = ['title', 'content', 'article_image']

user/forms.py
from django import forms


class RegisterForm(forms.Form):
    username = forms.CharField(max_length=25, label="Имя пользователя")
    password = forms.CharField(max_length=50, label="Пароль", widget=forms.PasswordInput)
    confirm = forms.CharField(max_length=50, label="Подтвердите пароль", widget=forms.PasswordInput)

    def clean(self):
        username = self.cleaned_data.get('username')
        password = self.cleaned_data.get('password')
        confirm = self.cleaned_data.get("confirm")
        if password and confirm and password!=confirm:
            raise forms.ValidationError("Ваш пароль не соответствует")
        values = {
            "username": username,
            "password": password
        }
        return values

class LoginForm(forms.Form):
    username = forms.CharField(label="Имя пользователя")
    password = forms.CharField(label="Пароль", widget=forms.PasswordInput)

blog/views.py
from django.shortcuts import render, HttpResponse, redirect, get_object_or_404, reverse
from .forms import ArticleForm
from django.contrib import messages
from .models import Blog, Comment
from django.contrib.auth.decorators import login_required


def articles(request):
    keyword = request.GET.get("keyword")
    if keyword:
        articles = Blog.objects.filter(title__contains=keyword)
        return render(request, 'articles.html', {"articles": articles})
    articles = Blog.objects.all()
    return render(request, 'articles.html', {"articles": articles})


def index(request):
    articles = Blog.objects.all()
    context = {"articles": articles}
    return render(request, 'index.html', context)


def about(request):
    return render(request, 'about.html')

def detail(request, id):
    article = get_object_or_404(Blog, id=id)
    comments = article.comments.all()
    return render(request, 'detail.html', {'article': article, "comments": comments})

@login_required(login_url = "user:login")
def dashboard(request):
    articles = Blog.objects.filter(author = request.user)
    context = {"articles": articles}
    return render(request, 'dashboard.html', context)

@login_required(login_url = "user:login")
def addArticle(request):
    form = ArticleForm(request.POST or None, request.FILES or None)
    if form.is_valid():
        article = form.save(commit=False)
        article.author = request.user
        article.save()
        messages.success(request, "Ваша статья успешно добавлена")
        return redirect('index')
    context = {"form": form}
    return render(request, 'addarticle.html', context)

@login_required(login_url = "user:login")
def updateArticle(request, id):
    article = get_object_or_404(Blog, id=id)
    form = ArticleForm(request.POST or None, request.FILES or None, instance=article)
    if form.is_valid():
        article = form.save(commit=False)
        article.author = request.user
        article.save()
        messages.success(request, "Ваша статья успешно обновлена")
        return redirect('index')
    return render(request, 'update.html', {"form":form})

@login_required(login_url = "user:login")
def deleteArticle(request, id):
    article = get_object_or_404(Blog, id=id)
    article.delete()
    messages.success(request, "Ваша статья успешно удалена")
    return redirect('blog:dashboard')


def addComment(request, id):
    article = get_object_or_404(Blog, id=id)
    if request.method == 'POST':
        comment_author = request.POST.get('comment_author')
        comment_content = request.POST.get('comment_content')
        newComment = Comment(comment_author=comment_author, comment_content=comment_content)
        newComment.article = article
        newComment.save()
    return redirect(reverse('blog:detail', kwargs={"id": id}))

kassa/views.py
from django.shortcuts import render

def privacy(request):
    return render(request, 'privacy.html')

def refund(request):
    return render(request, 'refund.html')

user/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.contrib.auth import login, logout, authenticate
from .forms import RegisterForm, LoginForm
from django.contrib import messages

def register(request):
    form = RegisterForm(request.POST or None)
    if form.is_valid():
        username = form.cleaned_data.get('username')
        password = form.cleaned_data.get("password")

        newUser = User(username = username)
        newUser.set_password(password)

        newUser.save()
        login(request,newUser)
        return redirect('index')

    context = {"form": form}

    return render(request, 'register.html', context)

def loginUser(request):
    form = LoginForm(request.POST or None)
    context = {"form": form}
    if form.is_valid():
        username = form.cleaned_data.get("username")
        password = form.cleaned_data.get("password")
        user = authenticate(username=username, password=password)
        if user is None:
            messages.info(request, "Your username or password is incorrect")
            return render(request, 'login.html', context)

        messages.success(request, "Welcome to our web site")
        login(request, user)
        return redirect('index')
    return render(request, 'login.html', context)

def logoutUser(request):
    logout(request)
    messages.success(request, "Вы успешно вышли из системы!")
    return redirect('index')

templates/about.html
{% extends "layout.html" %}
{% block title %} | О нас{% endblock %}
{% block body%}

    <div  style="background-color: #f3f5f7;">
        <h3 style="margin-top:50px; text-align:center; margin-bottom:50px;"><br>Как мы работаем</h3>
        <div style = "margin-bottom:50px; padding-left: 60px; padding-right: 60px; font-size:20px; font-family:sans-serif;">


            <p style="line-height:30px; margin-top:40px;"><b>Tezbilet.ru не занимается продажей авиабилетов.</b> Наша основная задача - помочь вам найти лучшее из того, что предлагают наши надежные партнеры по всему миру. Сам процесс покупки происходит на веб-сайте нашего партнера, чье предложение вам больше всего понравится.</p>
            <p>Tezbilet.ru не делает наценок и не берет комиссии и вознаграждения со своих пользователей. Свои комиссионные мы получаем, непосредственно, от наших партнеров, за то, что привлекаем клиентов на их веб-сайты.</p>
            <p>Мы сотрудничаем с огромным количеством агентств по всему миру и можем предложить широкий спектр маршрутов, различных акций и скидок. Прямая связь с авиакомпаниями и агентствами позволяет нам моментально обновлять тарифы и специальные предложения.</p>
            <p>Наши партнеры – это компании с высокой репутацией, доказавшие свою надежность и высокий профессионализм. Мы очень ценим доверие наших клиентов, без которого невозможен наш собственный рост. Поэтому, мы всегда тщательно отбираем компании, с которыми заключаем партнерство.</p>
            <p><b>Если у вас имеются вопросы по поводу приобретенных авиабилетов</b> или нужно внести какие-то изменения (сдать/обменять), рекомендуем обратиться к представителям компании, у которой был заказан билет.</p>
            <br><br><br>

            <h2 style="text-align:center; font-size:40px; color: #1b1b1b; margin-top:40px;">Почему клиенты выбирают нас?</h2><br><br>
            <div class="row row-cols-1 row-cols-md-2 g-4">
              <div class="col">
                <div class="card">
                  <div class="card-body">
                    <h5 class="card-title">Огромный выбор</h5>
                    <p class="card-text">Tezbilet сравнивает тысячи предложений от 725 авикомпаний мира, 45 агентств и 5 систем бронирования.</p>
                  </div>
                </div>
              </div>
              <div class="col">
                <div class="card">

                  <div class="card-body">
                    <h5 class="card-title">Надежный и бесплатный поиск</h5>
                    <p class="card-text">При выборе авиарейса, мы бесплатно направляем вас, к нашим проверенным партнёрам, которые продают билеты.</p>
                  </div>
                </div>
              </div>
              <div class="col">
                <div class="card">

                  <div class="card-body">
                    <h5 class="card-title">Онлайн-покупка авиабилетов — быстро и просто</h5>
                    <p class="card-text">У нас вы можете в пару кликов забронировать авиабилеты.</p>
                  </div>
                </div>
              </div>
              <div class="col">
                <div class="card">
                  <div class="card-body">
                    <h5 class="card-title">Никаких сборов или наценок</h5>
                    <p class="card-text">Цена, которую вы видите в результатах поисках именно та, которую вы будете платить.</p>
                  </div>
                </div>
              </div>
            </div>
        </div>
    </div>

{% endblock %}

templates/addarticle.html
{% extends 'layout.html' %}
{% load crispy_forms_tags %}
{% block title %} | Добавить статья{% endblock %}

{% block body %}

<div class="row">
      <div class="col-md-6 offset-md-3">
        <h1>Добавить статью</h1>
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.media }}
            {{ form | crispy }}<br>
            <button type="submit" class="btn btn-success">Добавить</button>
        </form>
      </div>
</div>

{% endblock %}

templates/articles.html
{% extends 'layout.html' %}
{% block title %} | Статьи {% endblock %}
{% block body %}

<div class="container">

    <header  class="py-5 bg-light border-bottom mb-4">
        <div  class="container">
            <div class="text-center my-5">
                <h1 style="color:#007BFF;" class="fw-bolder">Добро пожаловать на главную страницу блога!</h1>
                <p style="color:red; font-weight: bold;" class="lead mb-0">Все интересные статьи и факты здесь</p>
            </div>
        </div>
    </header>

    <form>
        <input type="text" name="keyword" class="input-sm"/>
        <button type="submit" class="btn btn-success">Поиск</button>
    </form>
    <hr>

</div>



<div class="row row-cols-1 row-cols-md-3 g-4">

{% if articles %}
    {% for article in articles %}
        <div class="card">
                <div class="article__thumbnail article__item">
                  <img class="article__thumbnail__img" src="{{ article.article_image_thumbnail.url }}"/>
                </div>
              <div class="card-body">
                <h5 class="card-title">{{ article.title }}</h5>
                <p class="card-text">{{  article.content|safe|truncatewords:20  }}</p>
              </div>
              <div class="card-body d-flex flex-column">
                    <a style="center" href="{% url 'blog:detail' article.id %}" class="btn btn-primary">Читать далее</a>
              </div>
        </div>
{% endfor %}
{% else %}
    <div class="col-md-10 offset-md-3">
            <div class="col-lg-8">
                <div class="aler alert-danger">Пока нет статей</div>
            </div>
        </div>
{% endif %}
    </center>
</div>


{% endblock %}

templates/dashboard.html
{% extends 'layout.html' %}
{% load crispy_forms_tags %}
{% block title %} | Панель приборов {% endblock %}

{% block body %}

<h3>Панель управление</h3>
<hr>
<p>
    Добро пожаловать в панель управления {{request.user.username}}
</p>
<hr>
<a class="btn btn-success" href = "/blog/addarticle">Добавить статью</a>
<hr>
{% if articles %}
    <table class="table">
      <thead>
        <tr>
          <th scope="col">Добавить статью</th>
          <th scope="col">Заголовок</th>
          <th scope="col">Автор</th>
          <th scope="col">Дата создания</th>
          <th scope="col">Обновлять</th>
          <th scope="col">Удалить</th>
        </tr>
      </thead>
      <tbody>
      {% for article in articles %}
        <tr>
          <th scope="row">{{article.id}}</th>
          <td><a href="{% url 'blog:detail' article.id %}">{{article.title}}<a/></td>
          <td>{{article.author.username}}</td>
          <td>{{article.created_date}}</td>
          <td><a class="btn btn-success" href="{% url 'blog:update' article.id %}">Update</a></td>
          <td><a class="btn btn-danger"  href="{% url 'blog:delete' article.id %}">Delete</a></td>
        </tr>
      {% endfor %}
      </tbody>
    </table>
{% else %}
    <div class="alert alert-danger">
        У вас пока нет статей
    </div>
{% endif %}

{% endblock %}

templates/detail.html
{% extends 'layout.html' %}
{% block title %} | {{ article.title }} {% endblock %}
{% block body %}



<div class="row">
    <div class="col-md-10 offset-md-3">
        <div class="col-lg-8">
        <!-- Post content-->
            <article>
                <!-- Post header-->
                <header class="mb-4">
                    <!-- Post title-->
                    <h1 class="fw-bolder mb-1">{{ article.title }}</h1>
                    <!-- Post meta content-->
                    <div class="text-muted fst-italic mb-2">Опубликовано {{article.created_date}} автором {{article.author.username}}</div>
                    <!-- Post categories-->
                    <!--- <a class="badge bg-secondary text-decoration-none link-light" href="#!">Web Design</a>
                    <a class="badge bg-secondary text-decoration-none link-light" href="#!">Freebies</a> --->
                </header>
                <!-- Preview image figure-->
                {% if article.article_image %}
                    <figure class="mb-4"><img class="img-fluid rounded" src="{{ article.article_image.url }}" alt="..." /></figure>
                <!-- Post content-->
                {% else %}
                {% endif %}
                <section class="mb-5">
                    {{article.content | safe}}
                </section>
            </article>
            <hr>
            <h4>Комментарии</h4><br>
                {% if comments %}
                    {% for comment in comments %}
                        <div class="media mb-4">
                        <div class="media-body">
                            <h5 class="mt-0">{{comment.comment_author}}</h5>
                           {{comment.comment_date}}<br>
                           {{comment.comment_content}}
                        </div>
                        </div>
                    {% endfor %}

                {% else %}
                    <div class="alert alert-danger">Комментариев пока нет, вы можете быть первым комментатором</div>
                {% endif %}
                <div class="card my-4">
                    <h5 class="card-header">Оставить комментарий:</h5>
                    <div class="card-body">
                    <form method = "post" action = "{% url 'blog:comment' article.id %}">
                        {% csrf_token %}

                        <div class="form-group">
                        <label>Имя</label>
                        <input name = 'comment_author' type="text" class="form-control"  placeholder="Андрей">
                        </div>

                        <div class="form-group">
                          <label>Ваше мнение</label>
                            <textarea name = 'comment_content' class="form-control" rows="3"></textarea>
                        </div><br>

                          <button type="submit" class="btn btn-primary">Отправлять</button>
                    </form>
                    </div>
                </div>
            </div>






    </div>
</div>




{% endblock %}

templates/includes/example.html
<nav class="navbar navbar-expand-lg navbar navbar-dark bg-primary">

  <div class="container-fluid">
  <a class="navbar-brand" href="{% url 'index' %}">Тезбилет</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
      <li class="nav-item active">
        <a class="nav-link active" aria-current="page" href="{% url 'blog:articles' %}">Статьи</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Dropdown link
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
    </ul>


    <ul class="navbar-nav ml-auto">
          {% if request.user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'blog:dashboard' %}">Dashboard</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{%  url 'user:logout' %}">Logout</a>
          </li>
        {% else %}
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{%  url 'user:register' %}">Register</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{%  url 'user:login' %}">Авторизоваться</a>
          </li>
        {% endif %}


      </ul>


  </div>
  </div>
</nav>

templates/includes/footer.html
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/css/all.min.css" integrity="sha512-HK5fgLBL+xu6dm/Ii3z4xhlSUyZgTT9tuc/hSrtw6uzJOvgRr2a9jyxxT1ely+B+xFAmJKVSTbpM/CuL7qxO8w==" crossorigin="anonymous" />
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

<footer class = "bg-dark text-white pt-5 pb-4">
    <div class="container text-center text-md-left">

        <div class="row text-center text-md-left">

            <div class='col-md-3 col-lg-3 col-xl-3 mx-auto mt-3'>
                <h5 class="text-uppercase mb-4 font-weight-bold text-warning">О нас</h5>
                <p>Тез Билет — крупнейший поисковик авиабилетов в Кыргызстане. Мы сравниваем все доступные варианты перелётов по вашему запросу, а потом направляем вас для покупки на официальные сайты авиакомпаний и агентств.
                    Стоимость авиабилета, которую вы видите на Тез Билет — финальная. Мы убрали все скрытые услуги и галочки.</p>
            </div>

            <div class="col-md-2 col-lg-2 col-xl-2 mx-auto mt-3">
                <h5 class="text-uppercase mb-4 font-weight-bold text-warning"> Сервисы</h5>
                <p>
                    <a href="https://c24.travelpayouts.com/click?shmarker=120716&promo_id=519&source_type=link&type=click&trs=36605" class="text-white" style="text-decoration:none;">Страхование</a>
                </p>

                <p>
                    <a href="https://c102.travelpayouts.com/click?shmarker=120716&promo_id=2958&source_type=link&type=click&trs=36605" class="text-white" style="text-decoration:none;">Сим карты</a>
                </p>

                <p>
                    <a href="https://c10.travelpayouts.com/click?shmarker=120716.120716&promo_id=2022&source_type=link&type=click&trs=36605" class="text-white" style="text-decoration:none;">Прокат авто</a>
                </p>

                <p>
                    <a href="https://c75.travelpayouts.com/click?shmarker=120716.120716&promo_id=1670&source_type=link&type=click&trs=36605" class="text-white" style="text-decoration:none;">Поиск попутчиков</a>
                </p>

                <p>
                    <a href="https://c57.travelpayouts.com/click?shmarker=120716.120716&promo_id=1669&source_type=link&type=click&trs=36605" class="text-white" style="text-decoration:none;">Прокат велосипедов</a>
                </p>

                <p>
                    <a href="https://c86.travelpayouts.com/click?shmarker=120716.120716&promo_id=2103&source_type=link&type=click&trs=36605" class="text-white" style="text-decoration:none;">Юридическая помощь</a>
                </p>

            </div>


            <div class="col-md-3 col-lg-2 col-xl-2 mx-auto mt-3">
                <h5 class="text-uppercase mb-4 font-weight-bold text-warning">Туры</h5>
                <p>
                    <a href="https://kruiz-online.tp.st/UzfsTOEA" class="text-white" style="text-decoration:none;">Морские круизы</a>
                </p>

                <p>
                    <a href="https://c140.travelpayouts.com/click?shmarker=120716.120716&promo_id=4338&source_type=link&type=click&trs=36605" class="text-white" style="text-decoration:none;">Пакет туры</a>
                </p>

                <p>
                    <a href="https://tp.media/r?marker=120716.120716&trs=36605&p=654&u=https%3A%2F%2Fweatlas.com%2F" class="text-white" style="text-decoration:none;">Экскурсии</a>
                </p>

                <p>
                    <a href="https://c140.travelpayouts.com/click?shmarker=120716.120716&promo_id=4338&source_type=link&type=click&trs=36605" class="text-white" style="text-decoration:none;">Свадебные туры</a>
                </p>

                <p>
                    <a href="https://c140.travelpayouts.com/click?shmarker=120716.120716&promo_id=4338&source_type=link&type=click&trs=36605" class="text-white" style="text-decoration:none;">Туры в Анталью</a>
                </p>

                <p>
                    <a href="https://c140.travelpayouts.com/click?shmarker=120716.120716&promo_id=4338&source_type=link&type=click&trs=36605" class="text-white" style="text-decoration:none;">Туры в ОАЭ</a>
                </p>

                <p>
                    <a href="https://c22.travelpayouts.com/click?shmarker=120716.120716&promo_id=201&source_type=link&type=click&trs=36605" class="text-white" style="text-decoration:none;">Трансферы</a>
                </p>

            </div>

            <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mt-3">
                <h5 class="text-uppercase mb-4 font-weight-bold text-warning">Контакты</h5>
                <!---<p>
                    <i class="fas fa-home mr-3"></i>ул. К. Датка 597, г.Ош
                </p> --->

                <p>
                    <i class="fas fa-envelope mr-3"></i>tezbilet@gmail.com
                </p>

                <p>
                    <i class="fas fa-phone mr-3"></i>+996 755 05 75 01
                </p>
                <hr>
                <p>

                    <a href="{% url 'kassa:privacy' %}" class="mb-4 font-weight-bold text-warning" style="text-decoration:none;">Правила</a>
                </p>

                <p>
                    <a href="{% url 'kassa:refund' %}" class="mb-4 font-weight-bold text-warning" style="text-decoration:none;">Возврат авиабилетов</a>
                </p>

            </div>

        </div>

        <hr class="mb-4">

        <div class="row align-items-center">
            <div class="col-md-7 col-lg-8">
                <p> Copyright 2020 All rights reserved by:
                    <a href="http://www.vadisoft.kg/" style="text-decoration:none;">
                        <strong class="text-warning">Vadi Soft</strong>
                    </a>
                </p>
            </div>


            <div class="col-md-5 col-lg-4">
                <div class="text-center text-md-right">
                    <ul class="list-unstyled list-inline">
                        <li class="list-inline-item">
                            <a href="https://www.facebook.com/profile.php?id=61552787621121" class="btn-floating btn-sm text-white" style="font-size:23px;"><i class="fab fa-facebook"></i></a>
                        </li>

                        <li class="list-inline-item">
                            <a href="https://www.instagram.com/tezbilet/" class="btn-floating btn-sm text-white" style="font-size:23px;"><i class="fab fa-instagram"></i></a>
                        </li>


                    </ul>
                </div>
        </div>
    </div>
    </div>

templates/includes/navbar.html
<nav class="navbar navbar-expand-lg navbar navbar-dark bg-primary">

  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'index' %}"><i class="bi bi-airplane"></i></a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'about' %}">О нас</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'blog:articles' %}">Блог</a>
        </li>
      </ul>

      <ul class="navbar-nav ml-auto">

        <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="https://c135.travelpayouts.com/click?shmarker=120716.120716&promo_id=4070&source_type=link&type=click&trs=36605">ЖД Билеты</a>
        </li>

        <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="https://www.facebook.com/profile.php?id=615527876211215"><i class="bi bi-facebook"></i></a>
        </li>

        <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="https://c135.travelpayouts.com/click?shmarker=120716.120716&promo_id=4070&source_type=link&type=click&trs=36605"><i class="bi bi-instagram"></i></a>
        </li>

        <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="https://play.google.com/store/apps/details?id=ru.air.tezbilet&pli=1"><i class="bi bi-google-play"></i></a>
        </li>





        <!--- {% if request.user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'blog:dashboard' %}">Панель</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{%  url 'user:logout' %}">Выйти</a>
          </li>
        {% else %}
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{%  url 'user:register' %}">Регистрация</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{%  url 'user:login' %}">Войти</a>
          </li>
        {% endif %} --->
      </ul>

    </div>
  </div>
</nav>

templates/index.html
{% extends "layout.html" %}
{% block title %} {% endblock %}
{% block body%}

<div class="container">
  <p>
      <script charset="utf-8" type="text/javascript" src="//www.tezbilet.kg/iframe.js"></script>
  </p>
</div>

<div class="container">
        <div class="text-center my-5">
            <h2 style="color:red;" class="fw-bolder">Блог: все интересные факты и статьи здесь!</h2>
        </div>
</div>


<section id="article">
<div class="row row-cols-1 row-cols-md-3 g-4">
    {% if articles %}
        {% for article in articles %}
            <div class="card">
                <div class="article__thumbnail article__item">
                  <img class="article__thumbnail__img" src="{{ article.article_image_thumbnail.url }}"/>
                </div>
                  <div class="card-body">
                    <h5 class="card-title">{{ article.title }}</h5>
                    <p class="card-text">{{  article.content|safe|truncatewords:10  }}</p>
                  </div>
                <div class="card-body d-flex flex-column">
                        <a style="center" href="{% url 'blog:detail' article.id %}" class="btn btn-primary">Читать далее</a>
                    </div>
            </div>
    {% endfor %}
    {% else %}
        <div class="col-md-10 offset-md-3">
                <div class="col-lg-8">
                    <div class="aler alert-danger">Пока нет статей</div>
                </div>
            </div>
    {% endif %}
        </center>
</div>
</section>




{% endblock %}